services:
  counter-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: counter-ui
    ports:
      - "8501:8501"
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./models:/app/models
      - ./runs:/app/runs
    command: ["uv", "run", "counter-ui", "--server.address=0.0.0.0", "--server.port=8501", "--server.headless=true"]
